# Generated by Django 5.0.6 on 2024-06-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('imgUrl', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=300)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
